#!/usr/bin/env python3
import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot relocation recovery curves from CSV."
    )
    parser.add_argument(
        "--input_csv",
        required=True,
        help="Input CSV path generated by multi_floor_navigation_node.",
    )
    parser.add_argument(
        "--output_png",
        default="reloc_recovery_curve.png",
        help="Output PNG path.",
    )
    parser.add_argument(
        "--linear_threshold",
        type=float,
        default=0.2,
        help="Linear error threshold in meters.",
    )
    parser.add_argument(
        "--angular_threshold",
        type=float,
        default=0.15,
        help="Angular error threshold in radians.",
    )
    return parser.parse_args()


def load_csv(csv_path: Path):
    elapsed_sec = []
    linear_error = []
    angular_error = []
    c_t = []
    pass_flags = []

    with csv_path.open("r", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        fieldnames = reader.fieldnames or []
        use_nom = "linear_error_nom" in fieldnames
        lin_key = "linear_error_nom" if use_nom else "linear_error"
        ang_key = "angular_error_nom" if "angular_error_nom" in fieldnames else "angular_error"
        for row in reader:
            elapsed_sec.append(float(row["elapsed_sec"]))
            linear_error.append(float(row[lin_key]))
            angular_error.append(float(row[ang_key]))
            c_t.append(float(row["C_t"]))
            pass_flags.append(int(row["pass_now"]))

    if not elapsed_sec:
        raise ValueError("CSV has no data rows.")

    pass_time = None
    for index, flag in enumerate(pass_flags):
        if flag == 1:
            pass_time = elapsed_sec[index]
            break

    return elapsed_sec, linear_error, angular_error, c_t, pass_time


def plot_curve(args):
    csv_path = Path(args.input_csv).expanduser().resolve()
    output_path = Path(args.output_png).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    elapsed_sec, linear_error, angular_error, c_t, pass_time = load_csv(csv_path)

    figure, axes = plt.subplots(2, 1, figsize=(10, 7), sharex=True)

    axes[0].plot(
        elapsed_sec,
        linear_error,
        label="linear_error_nom (m)",
        color="#1f77b4",
        linewidth=2.0,
    )
    axes[0].axhline(args.linear_threshold, color="#1f77b4", linestyle="--", linewidth=1.2, label="linear threshold")
    axes[0].set_ylabel("Linear Error (m)")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(loc="upper right")

    axes[1].plot(
        elapsed_sec,
        angular_error,
        label="angular_error_nom (rad)",
        color="#ff7f0e",
        linewidth=2.0,
    )
    axes[1].axhline(args.angular_threshold, color="#ff7f0e", linestyle="--", linewidth=1.2, label="angular threshold")
    axes[1].set_xlabel("Elapsed Time Since INIT_POSE (s)")
    axes[1].set_ylabel("Angular Error (rad)")
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(loc="upper right")

    if pass_time is not None:
        for axis in axes:
            axis.axvline(pass_time, color="green", linestyle="--", linewidth=1.2)
        axes[0].text(
            pass_time,
            max(linear_error),
            f" RELOC_PASS @ {pass_time:.2f}s",
            color="green",
            fontsize=9,
            va="top",
        )

    figure.suptitle("Relocation Recovery Curve")
    figure.tight_layout()
    figure.savefig(str(output_path), dpi=180)
    print(f"Saved figure to: {output_path}")


def main():
    args = parse_args()
    plot_curve(args)


if __name__ == "__main__":
    main()
